spring:
  application:
    name: jupjup-ticket-server-api

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
